src/components/Sidebar.tsx
src/components/__snapshots__/AccountNotifications.test.tsx.snap
src/components/__snapshots__/Sidebar.test.tsx.snap

fix: icon color

---

package.json
pnpm-lock.yaml
src/components/__snapshots__/AccountNotifications.test.tsx.snap
src/routes/Settings.test.tsx
src/routes/Settings.tsx
src/routes/__snapshots__/Settings.test.tsx.snap

Use atlaskit dialog modal for reset confirmation flow

refactor: use atlaskit modal dialog for reset flow

---

src/components/AccountNotifications.tsx

Order product grouping alphabetically for a deterministic order.  Prevents inconsistent state behavior particularly when interacting with a notification

feat: order product grouping alphabetically

---

src/__mocks__/electron.js
src/__mocks__/state-mocks.ts
src/components/AccountNotifications.tsx
src/components/__snapshots__/AccountNotifications.test.tsx.snap
src/context/App.test.tsx
src/context/App.tsx
src/electron/main.js
src/routes/Accounts.tsx
src/routes/Login.tsx
src/routes/Notifications.tsx
src/routes/__snapshots__/Accounts.test.tsx.snap
src/types.ts
src/utils/api/__snapshots__/client.test.ts.snap
src/utils/api/__snapshots__/request.test.ts.snap
src/utils/api/client.test.ts
src/utils/api/request.test.ts
src/utils/api/request.ts
src/utils/auth/types.ts
src/utils/auth/utils.test.ts
src/utils/auth/utils.ts
src/utils/comms.test.ts
src/utils/comms.ts
src/utils/errors.ts
src/utils/links.ts
src/utils/notifications/native.ts
src/utils/notifications/remove.test.ts
src/utils/notifications/remove.ts
src/utils/storage.test.ts
src/utils/storage.ts

Closes #98.
This is a breaking change and will require existing users to remove and re-add their account.  As such, I've updated the error instructions for `BAD_CREDENTIALS` error

refactor: secure auth

---

src/routes/Accounts.tsx
src/routes/__snapshots__/Accounts.test.tsx.snap

This feature isn't that useful in atlassify.  removing for now

refactor: remove primary/secondary account concept

---

src/components/notifications/NotificationRow.tsx
src/components/notifications/ProductNotifications.tsx
src/components/settings/NotificationSettings.tsx
src/hooks/useNotifications.ts
src/types.ts

Fixed notification state handling upon `mark as read`, `mark as unread`, `delay notification state`

fix: notification state on interactions

---

package.json

https://github.com/setchy/atlassify/milestone/4

build: prepare `v1.1.0` release

---

src/routes/Filters.tsx
src/routes/__snapshots__/Filters.test.tsx.snap

Place `category` and `read state` filters side-by-side

refactor: filter layout

---

docs/src/components/LatestRelease.astro
package.json

feat: restructure project

---

docs/src/components/LatestRelease.astro
docs/src/types.ts

use `isPrimary` to indicate which download link to display for macOS, linux and windows

build: macos arch types

---

package.json

https://github.com/setchy/atlassify/milestone/7

build: prepare `v1.3.1` release

---

package.json

https://github.com/setchy/atlassify/milestone/8

build: prepare `v1.4.0` release

---

package.json

https://github.com/setchy/atlassify/milestone/10

build: prepare `v1.6.0` release

---

package.json

https://github.com/setchy/atlassify/milestone/12

build: prepare `v1.6.1` release

---

package.json

https://github.com/setchy/atlassify/milestone/11

build: prepare `v1.7.0` release

---

package.json

https://github.com/setchy/atlassify/milestone/13

build: prepare `v1.8.0` release

---

package.json

https://github.com/setchy/atlassify/milestone/15

build: prepare `v1.9.0` release

---

package.json

https://github.com/setchy/atlassify/milestone/16

build: prepare `v1.10.0` release

---

package.json
sonar-project.properties

https://github.com/setchy/atlassify/milestone/17

build: prepare `v1.11.0` release

---

src/renderer/__mocks__/state-mocks.ts
src/renderer/components/notifications/NotificationRow.tsx
src/renderer/components/notifications/__snapshots__/AccountNotifications.test.tsx.snap
src/renderer/components/notifications/__snapshots__/NotificationRow.test.tsx.snap
src/renderer/context/App.tsx
src/renderer/routes/Filters.test.tsx
src/renderer/routes/Filters.tsx
src/renderer/routes/__snapshots__/Filters.test.tsx.snap
src/renderer/types.ts
src/renderer/utils/notifications/filters/actor.test.ts
src/renderer/utils/notifications/filters/actor.ts
src/renderer/utils/notifications/filters/category.ts
src/renderer/utils/notifications/filters/timeSensitive.ts
src/renderer/utils/notifications/filters/types.ts

feat(filters): actor filter

---

src/renderer/App.tsx
src/renderer/components/Sidebar.tsx
src/renderer/components/__snapshots__/Sidebar.test.tsx.snap
src/renderer/components/icons/UnreadIcon.test.tsx
src/renderer/components/icons/UnreadIcon.tsx
src/renderer/components/icons/__snapshots__/UnreadIcon.test.tsx.snap
src/renderer/components/notifications/AccountNotifications.tsx
src/renderer/components/notifications/NotificationRow.test.tsx
src/renderer/components/notifications/NotificationRow.tsx
src/renderer/components/notifications/ProductNotifications.tsx
src/renderer/components/notifications/__snapshots__/AccountNotifications.test.tsx.snap
src/renderer/components/notifications/__snapshots__/NotificationRow.test.tsx.snap
src/renderer/components/notifications/__snapshots__/ProductNotifications.test.tsx.snap
src/renderer/components/primitives/Header.tsx
src/renderer/components/primitives/__snapshots__/Header.test.tsx.snap
src/renderer/components/settings/AppearanceSettings.tsx
src/renderer/components/settings/SettingsFooter.tsx
src/renderer/components/settings/SettingsReset.tsx
src/renderer/index.tsx
src/renderer/routes/Accounts.tsx
src/renderer/routes/Login.tsx
src/renderer/routes/__snapshots__/Accounts.test.tsx.snap
src/renderer/routes/__snapshots__/Filters.test.tsx.snap
src/renderer/routes/__snapshots__/Login.test.tsx.snap
src/renderer/routes/__snapshots__/Settings.test.tsx.snap
src/renderer/utils/helpers.test.ts
src/renderer/utils/helpers.ts
tailwind.config.ts

refactor: migrate to new atlaskit iconset

---

package.json
sonar-project.properties

https://github.com/setchy/atlassify/milestone/18

build: prepare `v1.12.0` release

---

package.json

https://github.com/setchy/atlassify/milestone/19

build: prepare `v1.13.0` release

---

package.json
pnpm-lock.yaml

Revert "chore(deps): update @electron/notarize to v3"

---

package.json
pnpm-lock.yaml
src/renderer/routes/Login.tsx
src/renderer/routes/__snapshots__/Login.test.tsx.snap

fix: renderer crash on windows devices when using required text fields

---

src/renderer/utils/api/client.test.ts
src/renderer/utils/api/request.ts
src/renderer/utils/notifications/filters/product.ts
src/renderer/utils/products.ts

Had to redo this since not all v1.14.0 artifacts where correctly attached to the GitHub Release

build: prepare `v1.14.0` release

---

package.json

https://github.com/setchy/atlassify/milestone/22

build: prepare `v1.16.0` release

---

config/electron-builder.js
package.json
pnpm-lock.yaml

https://github.com/setchy/atlassify/milestone/23

build: prepare `v1.17.0` release

---

package.json
sonar-project.properties
src/renderer/i18n/locales/de.json
src/renderer/i18n/locales/es.json
src/renderer/i18n/locales/fr.json

https://github.com/setchy/atlassify/milestone/25

build: prepare `v1.19.0` release

---

src/renderer/utils/products.test.ts
src/renderer/utils/products.ts

Thank you @mvillis for finding this unhandled case

fix(products): handle notifications for Jira Work Management product sku

---

sonar-project.properties

https://github.com/setchy/atlassify/milestone/26

build: prepare `v1.20.0` release

---

package.json
sonar-project.properties

https://github.com/setchy/atlassify/milestone/27

build: prepare `v1.21.0` release

---

package.json
pnpm-lock.yaml

Revert "chore(deps): update react-router-dom to v7.7.0"

---

package.json
pnpm-lock.yaml

Revert "chore(deps): update typescript to v5.9.2"

---

package.json
sonar-project.properties

https://github.com/setchy/atlassify/milestone/30

build: prepare `v2.0.0` release

---

package.json
sonar-project.properties

https://github.com/setchy/atlassify/milestone/33

build: prepare `v2.3.0` release

---

package.json
sonar-project.properties
src/renderer/utils/api/request.ts

https://github.com/setchy/atlassify/milestone/35

build: prepare `v2.5.0` release

---

.github/workflows/publish.yml
package.json
sonar-project.properties

https://github.com/setchy/atlassify/milestone/36

build: prepare `v2.6.0` release

---

package.json
sonar-project.properties

https://github.com/setchy/atlassify/milestone/37

build: prepare `v2.7.0` release

---

package.json
sonar-project.properties

https://github.com/setchy/atlassify/milestone/39

build: prepare `v2.8.1` release
